name: 'build-test'
on:
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/**'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '